### ISSUE TITLE
Does StiefelGatedRecurrentUnit implements return_sequence?

### ISSUE THREAD

**Issue by v3551G** [v0lta/Complex-gated-recurrent-neural-networks#5]
In the self-defined RNN subclass-StiefelGatedRecurrentUnit, does it implements  the function of parameter-return_sequence as in tf.keras.layers.LSTM?

**Comment by v0lta** [comment]
It does not, because tf.keras.layers.LSTM implements an entire layer. It later accepts inputs of the form [batch, timesteps, feature].
The StiefelGatedRecurrentUnit implements a tf.nn.rnn_cell.RNNCell which is just a single timestep with [batch, feature] inputs.

**Comment by v3551G** [comment]
ok, thank you.
