### ISSUE TITLE
Performance issues in custom_optimizer.py

### ISSUE THREAD

**Issue by JamesCao2048** [v0lta/Complex-gated-recurrent-neural-networks#6]
Hello, I found that in custom_optimizer.py,  [init_rms](https://github.com/v0lta/Complex-gated-recurrent-neural-networks/blob/e968ebe3d76584176ea71f7bc233406124f8c649/custom_optimizers.py#L66) and [init_eps](https://github.com/v0lta/Complex-gated-recurrent-neural-networks/blob/e968ebe3d76584176ea71f7bc233406124f8c649/custom_optimizers.py#L70) are repeatedly created in the loop. As they ratain same in each iteration,  I think they should be moved before the loop to avoid creating redundant nodes in the tf computation graph.

The same issue exists [here](https://github.com/v0lta/Complex-gated-recurrent-neural-networks/blob/e968ebe3d76584176ea71f7bc233406124f8c649/human_motion_exp/src/custom_optimizers.py#L59)

Looking forward to your reply.  Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by v0lta** [comment]
Hi James, good catch. I am happy to accept a PR for this one :+1: .

**Comment by v0lta** [comment]
Okay merged! Thanks.
