### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by vkothapally** [v0lta/Complex-gated-recurrent-neural-networks#8]
Hi Moritz, I was just curious to know if you have a PyTorch implementation of this repo.

**Comment by v0lta** [comment]
Dear @vkothapally thanks you for your interest in this work. Unfortunately, the code I have for this repository is in Tensorflow only.

**Comment by vkothapally** [comment]
Hey Moritz,

Thank you for your prompt response. Will you be willing to work with me to create a Pytorch repo for this? This will be very useful for many researchers, including myself. I'm working on something where I believe using complex GRUs will help improve performance. If you are interested, please let me know. We can collaborate and get this up and running in a few days because you have all of the necessary module expertise.

PS: This work will be used in my Ph.D. defense, which I hope to complete by December. It would be greatly appreciated if you could assist me with this.



Thank you.


Best,

Vinay Kothapally

Ph.D. Candidate

Department of Electrical Engineering

Robust Speech Technologies Lab (RSTL)

Center for Robust Speech Systems (CRSS)

The University of Texas at Dallas


________________________________

**Comment by v0lta** [comment]
I have chosen Tensorflow three years ago because complex number support wasn't there in PyTorch yet. The situation has changed now ( https://pytorch.org/docs/stable/complex_numbers.html ). I already have a Stiefel-optimizer in Pytorch, if you create a repository we could port the cell together.

**Comment by vkothapally** [comment]
Hi Moritz,

Thanks for the response. I haven’t worked on Stifel manifold optimization before. So it would be a learning process for me. I will create the repo today and add you. Let me know how I will be helpful to you so that we can port it.

Best,
Vinay Kothapally

On Oct 17, 2021, at 7:58 AM, Moritz Wolter ***@***.***> wrote:

﻿

I have chosen Tensorflow three years ago because complex number support wasn't there in PyTorch yet. The situation has changed now ( https://pytorch.org/docs/stable/complex_numbers.html<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpytorch.org%2Fdocs%2Fstable%2Fcomplex_numbers.html&data=04%7C01%7CVinay.Kothapally%40utdallas.edu%7C1ffd58fa2f3d4f5d56bc08d9916dd310%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637700723186241892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IPVD8GSGjsPbrLmXAUpwVZvZme3%2Bys1J0dIPmmlCiPc%3D&reserved=0> ). I already have a Stiefel-optimizer in Pytorch, if you create a repository we could port the cell together.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fv0lta%2FComplex-gated-recurrent-neural-networks%2Fissues%2F8%23issuecomment-945115689&data=04%7C01%7CVinay.Kothapally%40utdallas.edu%7C1ffd58fa2f3d4f5d56bc08d9916dd310%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637700723186251887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UtCwHfwM3RgG5AvzdEah%2FyibsxjxhTaCK1QVLf5CDhE%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFTUQ7YCA3GMKSXCDLRWDA3UHLB7RANCNFSM5F6SXEUQ&data=04%7C01%7CVinay.Kothapally%40utdallas.edu%7C1ffd58fa2f3d4f5d56bc08d9916dd310%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637700723186251887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M6gj%2B%2FHN6z6baYsnvWh2uaQtFpo6FHVu95N4Tb1PTrU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CVinay.Kothapally%40utdallas.edu%7C1ffd58fa2f3d4f5d56bc08d9916dd310%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637700723186261884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0o9%2B50DKng0JyNd8poaR07V5nkGoSlxr73rEvImSVv4%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CVinay.Kothapally%40utdallas.edu%7C1ffd58fa2f3d4f5d56bc08d9916dd310%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637700723186261884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9VDLFbrRmVM2unEJZOIL8vZHPHRgk9vgT8FCPDfiYWM%3D&reserved=0>.
